### ISSUE TITLE
Share link not working

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#100]
Reproduce

1. create a graphml file 
2. click share and copy the url
3. Go to that url

You will not find anything there 

@pradebaan assign it to me, Will make PR for this shorty around next week

**Comment by pradeeban** [comment]
I get the "Error: URI Too Long" when I go to that URL.

Is it the same error you are getting?

**Comment by pradeeban** [comment]
I wonder whether we should just remove the "Share" option from there. I don't remember using that feature ever. https://github.com/ControlCore-Project/concore-editor/issues/97#issuecomment-1444071973

**Comment by parteekcoder** [comment]
> I get the "Error: URI Too Long" when I go to that URL.
> 
> Is it the same error you are getting?

No, i got an empty editor, there wasn't any error in my case

What browser you are using

**Comment by pradeeban** [comment]
For both Chrome and Firefox (on MacOS), I get "Error: URI Too Long" in an otherwise empty browser tab.

**Comment by parteekcoder** [comment]
> I wonder whether we should just remove the "Share" option from there. I don't remember using that feature ever. [#97 (comment)](https://github.com/ControlCore-Project/concore-editor/issues/97#issuecomment-1444071973)

yeah, we can disable or remove that option for now 
@pradeeban what you say shall I remove it from the page for now

**Comment by pradeeban** [comment]
@parteekcoder Sure, please create a PR, if it is a trivial fix with very few changes to just one file. 
If it needs edits to many files, we can ignore the bug for now (while keeping the bug report open).

**Comment by parteekcoder** [comment]
@pradeeban yeah pradeeban actually changes can be of one line but I have to analyze the whole code related to share ,

So now will remove share button from the scrren by commenting code

Or leave it for now

But I will ensure you in 1 or 2 days I will solve it

**Comment by pradeeban** [comment]
@parteekcoder There is no rush. You can take your time. 

The bug is not critical. It is an unused, broken feature. Either we fix the feature (if it is trivial) or remove the option from the front end (if that is trivial). We can leave this bug report open if both take a significant effort.

This is my recommended approach for all the uncritical bugs of the concore editor.

**Comment by pradeeban** [comment]
> I wonder whether we should just remove the "Share" option from there. I don't remember using that feature ever. [#97 (comment)](https://github.com/ControlCore-Project/concore-editor/issues/97#issuecomment-1444071973)

With your latest findings on #107, I would say let's just remove the "Share" button from the front end from now.

You can keep the functionality hanging around so that this can be fixed later if needed later. 

But for now, just removing the button from the display should be sufficient. That should be a one-line change if I understood the code correctly.

**Comment by pradeeban** [comment]
Closed with the merge of #110. The "Share" option is a Won't Fix now.
