### ISSUE TITLE
related to issue #100

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#107]
As to solve issue #100 it requires multiple steps 

1. to short the URL produced , as now it depends on the components in the graphml file
2.  Then decrypting the URL to retrive again graphjson

So here I am opening this issue to first shorten the URL using some hashing techniques which produces some fixed size hashstring 

@pradeeban what do you think about this strategy, so that I can start working on it in steps mentioned above

**Comment by pradeeban** [comment]
@parteekcoder, that seems like an involved approach with a significant time investment from you to implement that and another time investment from you and me (or another committer) to test this.

To test this, we should not only test that the share link is working, but also that the performance does not degrade with your proposed two steps approach of shortening the URL and decrypting it.

We don't want such a time investment on a feature that no one uses in concore editor. The same comment applies to the actual GSoC coding period as well. 

The actual fix may just be removing the "Share" button and be done with this for concore editor. (concore editor is a fork of DHGWorkflow. We are not actively maintaining the DHGWorkflow anymore. But "Share" option still works in DHGWorkflow. It is broken in concore editor only - and we did not care much since it was never used.)

Do you remember the "Contribute" option in concore, a GSoC project? That allows users to contribute their workflows/studies to concore repository and share through that mechanism. That is the approach we want to go ahead with for "Sharing."

I am going to close this bug now (while keeping the #100 open). For #100, if you think you can just remove the "Share" button from the front-end and send a PR, I will merge it. It is a useless button that is crowding the menu.

**Comment by parteekcoder** [comment]
ok @pradeeban I will remove it for now time being but I will ensure I will look into it in future as it is interesting to solve

**Comment by parteekcoder** [comment]
@pradeeban 
can you please explain which option are you talking about Here 
```
Do you remember the "Contribute" option in concore, a GSoC project? That allows users to contribute their workflows/studies to concore repository and share through that mechanism. That is the approach we want to go ahead with for "Sharing."
```

**Comment by pradeeban** [comment]
This.

[10] A "contribute" action to concore studies.

https://github.com/NISYSLAB/Emory-BMI-GSoC/blob/main/README.md

Given your time investment in the "Share" option, I thought you would be interested in that project idea. Please let me know if you have more questions (since that project idea is not discussed adequately yet).

Feel free to open a separate discussion at https://github.com/ControlCore-Project/concore/discussions on the "Contribute" action if you have additional questions on that GSoC project idea.

**Comment by parteekcoder** [comment]
Yeah , but I also think that it will not degrade to the performance as the scenario is

Sender :- will only encrypt the graphjson
Receiver :- will only decrypt it 

So they both only perform one step, the time is only taken by hashing algorithm which I thing is not much large

But not an issue we can improve it later on ,but I like your thought about performance

**Comment by pradeeban** [comment]
Yes, those are valid points. That's the reason for my proposal to just remove (or comment out) that "Share" button from the display. Do not remove the whole functionality. So, in the future, when time permits and need arises, we can fix this properly.
