### ISSUE TITLE
Uploading studies and programs

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#134]
hey @pradeeban ,

As we are sending files to the server so there should be any GUI component which allow users to select the associated graphs and programs to upload when build is clicked 

Need: As multiple graphs and programs can be open so user to choose one

please assign if this is required functionality

**Comment by pradeeban** [comment]
The way we are handling right now is, assuming the studies and programs locally exist already. Otherwise, "Save As" saves it locally. We don't really have a server implementation with concore in a cloud server with concore-editor in a local browser. We had plans for that. But not anymore. It is a complex undertaking, considering the security features (which we lack).

"As we are sending files to the server"
We are not. Are you referring to the "Contribute" option? That will send the files to the concore github repository as a pull request.

The build merely invokes the FRI REST APIs in concore, which are available locally. "The concore server" is just a local backend as of now, and its REST APIs are provided by the Flask-based FRI in concore.

Closing as "Won't Fix."
