### ISSUE TITLE
ColorBox

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#136]
hey @pradeeban 

I see a `ColorBox` component which is used to pick the color , But I think it is not implemented fully that's why it is not in use now

please assign me I will fully implement it to enhance UX experience

**Comment by pradeeban** [comment]
Can you please elaborate?

If there are unused components, there are two reasons:
1. They were left unimplemented because of lack of time.
2. They were implemented as part of DHGWorkflow, but removed later in concore-editor as we realized it is an unneeded feature. This looks like such a feature.

Do you have a use for this feature?

For example, in DHGWorkflow, you can choose the color of edges and nodes. We intentionally removed that in concore-editor.

**Comment by pradeeban** [comment]
(because, what we need is a minimal front-end for concore. If you are in doubt, you can also check DHHWorkflow to see the colors are supported in it).

At some point, we should remove any useless code that is hanging around. But please do not attempt that refactoring at this point.

**Comment by parteekcoder** [comment]
yeah
"For example, in DHGWorkflow, you can choose the color of edges and nodes. We intentionally removed that in concore-editor."

I am talking about this feature , actually there is commented code present in all files related to ColorBox which I think need some integration

**Comment by pradeeban** [comment]
ah yes, ideally, the unused code should have been removed. But we were reaching the end of GSoC 2022 and were not confident in removing altogether. So we left the code commented and hanging around.

The feature should not exist as of now. The color means nothing in concore-editor.

I am closing this issue as "Won't Fix."
