### ISSUE TITLE
Edits to graphml files are not reflected in the browser session

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#54]
To reproduce:
* Upload a folder of studies. (such as demo of concore).
* After editing a GraphML file, save it, close it, and reopen it.
* Your changes won't be shown (although they are correctly stored in the file system).
* To see the changes, you must re-upload the folder.

**Comment by Aviral09** [comment]
This happens because the "File Objects" in the file browser list are old(before the changes were made). There is no dynamic way to refresh the file objects other than reinitializing them using file handles.

The solution is to getFile from the fileHandle at all times, ensuring the latest version is opened.
But the tradeoff is that we must 'await' every time for the getFile operation to complete, which may cause a few seconds of delay. This is not significant, and I believe should not be noticeable as well.

I will send a PR with updates shortly. This solution will also address issue #53.

**Comment by pradeeban** [comment]
Thanks. This is fixed. But now I notice https://github.com/ControlCore-Project/concore-editor/issues/57 (Probably an unrelated issue). This is observed in Chrome.
