### ISSUE TITLE
Intermittent weird issues with the "Save" button for programs and studies.

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#58]
Sometimes, the "Save" button (for both studies and programs) expect to be clicked thrice to save a program or a study.
Once, it threw a "Switch to Edge/Chrome!" while I was trying to save a program on Chrome on MacOS. The cache is cleared.

See the ![Screenshot](https://github.com/ControlCore-Project/concore-editor/blob/main/figures/chrome-chrome.png).

**Comment by Aviral09** [comment]
This is unexpected behaviour. However, I believe it is due to the time it takes to detect which browser you're using.

As soon as it detects the user is using Chrome, it replaces the old version "Upload directory" button with the new version button. This process is almost instantaneous (making use of useEffect in React).

But sometimes, due to unforeseen reasons, this update may take a little longer and thus, in between, if the user clicks the button, it defaults to the firefox behaviour. 

I will perform more testing and look for a workaround; in the general case, it won't happen however.

**Comment by parteekcoder** [comment]
@pradeeban is this issue still opened or closed as there is a PR for this

**Comment by pradeeban** [comment]
This is still open.

**Comment by parteekcoder** [comment]
@pradeeban i have a created a PR for this issue and now it is correctly saving files

Actually the issue was in save function graph donot have fileHandle key so that's why entering else section

**Comment by parteekcoder** [comment]
hey @pradeeban please review now , it is working on all browser

**Comment by pradeeban** [comment]
It is confusing what is going on here. @Aviral09 implemented this for Chrome and it works fine except for intermittent issues on Chrome.

@Aviral09 pls review @parteekcoder's pull request if you have time.

**Comment by Aviral09** [comment]
Okay I will review the same.

**Comment by parteekcoder** [comment]
hey @Aviral09 please tell me what's wrong so that I can correct , you can fork my branch and check after deploy

**Comment by pradeeban** [comment]
Couldn't reproduce as lately with @Rahuljagwani's fixes #103. Closing as "Cannot reproduce" for now.
