### ISSUE TITLE
No user Manual Document available for concore-editor

### ISSUE THREAD

**Issue by shivangvijay** [ControlCore-Project/concore-editor#67]
I have been using concore-editor for quite a few days, but I still don't have complete clarity on using all the features or buttons available in the editor. It will be too helpful if Manual Document is available for concore-editor.

**Comment by pradeeban** [comment]
Thanks for the report, @shivangvijay. This is, unfortunately, true.

The GSoC contributor on the concore editor project this year should pay more attention to the documentation aspects too.

**Comment by Aviral09** [comment]
I recognise this as a significant concern as well. There is not enough documentation for the features I implemented during my GSoC term last year.
@pradeeban I have been caught up with work earlier, but we can probably now work on the documentation. Furthermore, I believe along with written documentation, we can record workflow videos and publish them on youtube for first-time users.

**Comment by pradeeban** [comment]
Yes, it was the case for GSoC 2021 as well. It is fine, we can focus more on documentation for this year.

**Comment by parteekcoder** [comment]
hey @pradeeban do you have any deployed project for the docs of concore editor , so that I can improve the docs

**Comment by pradeeban** [comment]
We do not have the user-level documentation. Expecting potential contributors before GSoC to write the documentation is unfair for a few reasons: 
* because they are not famiiar with the code base and the expected functionality yet.
* because the code contributions we expect from the potential contributors are to judge that they can do the coding.

The contributor (hopefully if Emory BMI is accepted to GSoC 2023 and if we get a contributor working on the project idea [1], should work on the documentation once the GSoC starts - perhaps during the community bonding period or, more realistically, in parallel with the project development (during the coding).

Documentation and testing should go in parallel with coding (in any project, actually).

**Comment by pradeeban** [comment]
This is largely implemented by the GSoC students this year. So, closing.
