### ISSUE TITLE
repeated Save As button

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#68]
Recreate issue
1)open the app
2) top left corner. click create
3) in the new window appeared you see 2 save as buttons on at top and other at the bottom
![Uploading Screenshot_20230207_210609.png…]()

![Screenshot_20230207_210630](https://user-images.githubusercontent.com/100110395/217290998-5926f361-7679-4a60-a744-6b7c5bc4225f.png)
![Screenshot_20230207_210640](https://user-images.githubusercontent.com/100110395/217291051-caeede6d-666e-4eba-b243-8bf0447c4366.png)

which is of no use and create confusion

**Comment by pradeeban** [comment]
Thanks for the report, @parteekcoder.

But this is intentional. Programs tend to get really long. So, we wanted an ability to save by the end of file even when the program is really long.

There could be a better implementation such as a floating "Save As" button. But that is not a critical feature.

**Comment by parteekcoder** [comment]
hey @pradeeban i want to work on this project this year in GSOC can u please guide me
