### ISSUE TITLE
npm start failed on windows

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#69]
reproduce issue
1)clone the repo in window
2) npm install
3) npm run start

![image](https://user-images.githubusercontent.com/100110395/217304071-2633431a-c4e6-47a8-bfd4-90558b8bd16f.png)

**Comment by pradeeban** [comment]
Thanks, this is a valid issue. Please attempt your fix and let me know if it worked.

The challenge is we should ensure the fix won't break the execution for other operating systems, such as Linux and MacOS. Usually, line breaks are tricky, and fixing one operating system could break another.

**Comment by parteekcoder** [comment]
@pradeeban please review my PR , I have solved 2 issues

**Comment by pradeeban** [comment]
Please make sure to send one PR per issue. While bundling up two fixes in a single PR is not a huge issue, that means, we have to wait until we test both fixes before the merge.

The "Save" issue is intermittent and occurs for both studies (graphml) and programs (.py, .cpp, ...). Your fix looks into only graphml.

I am not a front-end expert. Since this works usually and only happens intermittently, do you have any idea why that must be the case?

**Comment by parteekcoder** [comment]
bcoz in saving we are accepting only .graphmp files but i can increse the choices to fix this

**Comment by pradeeban** [comment]
No, that issue appears also for the "Save" button for programs, as in below.
![image](https://raw.githubusercontent.com/ControlCore-Project/concore-editor/main/figures/save-button-issue.png)

Again, these are intermittent issues in the Save options. Therefore, the fixes may not be as straightforward.

**Comment by pradeeban** [comment]
Hi @parteekcoder, please feel free to attend to any issues at your leisure. We will need extensive reviews before accepting the pull requests.

**Comment by parteekcoder** [comment]
@pradeeban where can i find your GSOC projects

**Comment by Rahuljagwani** [comment]
> one solution is that we can write linebreak-style:0 in .eslintric

It can solve the problem for a particular windows but for other it will be troublesome (may be for unix or so). Therefore better will be to provide a particular method in the documentation for windows while installing.

**Comment by pradeeban** [comment]
@parteekcoder please find the project ideas at https://github.com/NISYSLAB/Emory-BMI-GSoC/ and go through the links in the repository as well for more details.

**Comment by Aviral09** [comment]
Hey @parteekcoder and @Rahuljagwani, this can be fixed by making a single line change in the installed environment. 
In the file `.eslintrc.json`, in the `rules` object please add the following line -
1. If using windows -  `"linebreak-style": ["error", "windows"]`
2. If using unix - "linebreak-style": ["error", "UNIX"]

I'll add the same in the readme as well.

**Comment by pradeeban** [comment]
Thanks @Aviral09. I have merged your pull request for the documentation fix.

Can we find the OS (linux/Mac OS vs. Windows) and create an if/else statement to run the correct line for the relevant OS instead of manually changing this line?

Keeping this issue open until this is addressed appropriately.

**Comment by Aviral09** [comment]
Okay sir, added a more elegant solution. The Readme update isn't required anymore.

**Comment by pradeeban** [comment]
Thanks, @Aviral09. This is merged now to the main branch.

@parteekcoder, please feel free to reopen this issue if you still encounter problems.
